plugins:
  fixme:
    enabled: true
exclude_paths:
- "**.rb"
- "**.css"
- "**.html"
- "**/migrations/**"
- "**/south_migrations/**"
- "scratchpad/**"
- "**/tests/**"
- "settings/**"
- "subprocess42.py"

