version: 2
jobs:
  build:
    working_directory: ~/example-foobar
    docker:
      - image: ruby:2.4
        environment:
          CODECLIMATE_REPO_TOKEN: "490eb0f55f0afad6ec34f6c4857c5e1a70553b3457db0f5fd81e1ddb62074fc4"
    steps:
      - checkout
      - type: cache-restore
        key: example-foobar-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - type: cache-save
        key: example-foobar-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run: bundle exec rspec && bundle exec codeclimate-test-reporter
